### ISSUE TITLE
Warnings issued when building on ubuntu-19.10

### ISSUE THREAD

**Issue by dmknutsen** [nasa/cFE#493] opened 2020-01-27 15:56 UTC
**Describe the bug**
The warnings contained in the attached file are issued when building on ubuntu-19.10.

**To Reproduce**
Nominal build process

**Expected behavior**
Clean build

**System observed on:**
Oracle VM VirtualBox
OS: ubuntu-19.10
Version: cFE 6.7.5.0, OSAL 5.0.5.0, PSP 1.4.3.0,

**Reporter Info**
Dan Knutsen
GSFC/NASA

**Comment by dmknutsen** [comment] 2020-01-27 16:01
[Errors_for_Isssue_493.txt](https://github.com/nasa/cFE/files/4117989/Errors_for_Isssue_493.txt)

**Comment by jphickey** [comment] 2020-01-27 19:40
This should be fixed by #313 

However - I'm curious what version of GCC this is using and if you are cross compiling or building with SIMULATION=native?  Previously, GCC would only report possible mis-alignment issues on architectures that had strict alignment requirements.  It is possible in the newest GCC versions that they might warn even if the target CPU does not need the alignment?

Either way, I do have a fix for this, but it is waiting in the wings until I have time to rebase it and submit a pull request.

**Comment by dmknutsen** [comment] 2020-01-27 20:09
I am using gcc version 9.2.1 and I am building with SIMULATION=native.

Also, I suspect you are correct with the warnings being isolated to newer GCC versions as I only see it on my ubuntu 19.10 VM (GCC version 9.2.1) and not on my ubuntu18.4.3 VM (GCC version 7.4.0).

**Comment by skliper** [comment] 2020-05-19 18:56
@dmknutsen Could you confirm the warnings have been resolved?

**Comment by dmknutsen** [comment] 2020-05-20 12:22
Yep.  Just rebuilt this morning and ran software/unit tests.  Everything looks good now.

**Comment by skliper** [comment] 2020-05-20 12:42
Duplicate of the other memory alignment/warning tickets.  Resolved.

**Closed by skliper** 2020-05-20 12:42 UTC
Labels: duplicate
