### ISSUE TITLE
Duplicate CFE error codes

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#616] opened 2020-04-15 02:48 UTC
**Is your feature request related to a problem? Please describe.**
While coding fixes for another ticket, happen to stumble upon two CFE ES error codes with the same value.

https://github.com/nasa/cFE/blob/60a5f6580d1e737f46efce0418aba5b8dac6df6a/fsw/cfe-core/src/inc/cfe_error.h#L617-L634

**Describe the solution you'd like**
Should have unique/distinguishable values

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment] 2020-09-09 18:01
Duplicate of #846

**Closed by skliper** 2020-09-09 18:01 UTC
Labels: duplicate
